# docker-compose.yml

version: '3'
services:

  frontend:
    build: ./frontend 
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    depends_on: 
      - db
  
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql

volumes: 
  dbdata: